version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.16.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: |
            make dep
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Build AMD64
          command: |
            make ENV_BUILD_IDENTIFIER=$CIRCLE_TAG ENV_BUILD_VERSION=$(echo $CIRCLE_SHA1 | cut -c1-7) build
      - run:
          name: Install Cross-Platform Dependencies
          command: |
            sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install gcc-arm-linux-gnueabi libc6-dev-armel-cross gcc-arm-linux-gnueabihf libc6-dev-armhf-cross gcc-aarch64-linux-gnu libc6-dev-arm64-cross
            sudo ln -s /usr/include/asm-generic /usr/include/asm
      - run:
          name: Build ARM
          command: |
            make ENV_BUILD_IDENTIFIER=$CIRCLE_TAG ENV_BUILD_VERSION=$(echo $CIRCLE_SHA1 | cut -c1-7) build-cross-plat
      - store_artifacts:
          path: ~/repo/dist
